name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8

      - name: Install Dependencies
        run: |
          gem install standard
          bundle install

      - name: Run StandardRB
        run: standardrb

  test:
    name: Run RSpec Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8

      - name: Install Dependencies
        run: bundle install

      - name: Run RSpec
        run: bundle exec rspec